[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[build-system]
requires = ["setuptools==44.0"]
build-backend = "setuptools.build_meta"
