# setup for Marius
FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04

ENV TZ=US

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update

RUN apt install -y g++ \
         make \
         wget \
         unzip \
         vim \
         git \
         python3-pip \
         build-essential \
         python-dev \
         libpq-dev

# install cmake 3.20
RUN wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0-linux-x86_64.sh \
    && mkdir /opt/cmake \
    && sh cmake-3.20.0-linux-x86_64.sh --skip-license --prefix=/opt/cmake/ \
    && ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

# install pytorch
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 && pip3 install docutils==0.17

# install Marius
RUN git clone https://github.com/marius-team/marius.git && cd marius && pip3 install .

# install debconf-set-selections & systemctl
RUN apt-get install debconf

RUN apt-get install systemctl

# install mysql-8
RUN echo "mysql-community-server mysql-community-server/root-pass password password" | debconf-set-selections

RUN echo "mysql-community-server mysql-community-server/re-root-pass password password" | debconf-set-selections

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server

# Adding a run.sh script to initialize things
COPY run.sh /usr/local/bin/run.sh

RUN chmod +x usr/local/bin/run.sh
