function(add_pybind11_module MODULE_NAME MODULE_SOURCES)
    message(STATUS "Adding pybind11 module: ${MODULE_NAME}")
    message(STATUS "Adding pybind11 module sources: ${MODULE_SOURCES}")
    pybind11_add_module(${MODULE_NAME} ${MODULE_SOURCES})
    target_link_libraries(${MODULE_NAME} PRIVATE ${PROJECT_NAME} ${TORCH_PYTHON_LIBRARY})
endfunction()

file(GLOB_RECURSE CONFIG_BINDINGS ${project_BINDINGS} ${project_BINDINGS_DIR}/configuration/*.cpp)
file(GLOB_RECURSE DATA_BINDINGS ${project_BINDINGS} ${project_BINDINGS_DIR}/data/*.cpp)
file(GLOB_RECURSE NN_BINDINGS ${project_BINDINGS} ${project_BINDINGS_DIR}/nn/*.cpp)
file(GLOB_RECURSE MANAGER_BINDINGS ${project_BINDINGS} ${project_BINDINGS_DIR}/manager/*.cpp)
file(GLOB_RECURSE PIPELINE_BINDINGS ${project_BINDINGS} ${project_BINDINGS_DIR}/pipeline/*.cpp)
file(GLOB_RECURSE REPORT_BINDINGS ${project_BINDINGS} ${project_BINDINGS_DIR}/reporting/*.cpp)
file(GLOB_RECURSE STORAGE_BINDINGS ${project_BINDINGS} ${project_BINDINGS_DIR}/storage/*.cpp)

add_pybind11_module(_config "${CONFIG_BINDINGS}")
add_pybind11_module(_data "${DATA_BINDINGS}")
add_pybind11_module(_nn "${NN_BINDINGS}")
add_pybind11_module(_manager "${MANAGER_BINDINGS}")
add_pybind11_module(_pipeline "${PIPELINE_BINDINGS}")
add_pybind11_module(_report "${REPORT_BINDINGS}")
add_pybind11_module(_storage "${STORAGE_BINDINGS}")

add_custom_target(bindings)
add_dependencies(bindings _config _data _manager _nn _pipeline _report _storage)
