model:
  learning_task: LINK_PREDICTION
  encoder:
    train_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 32
      - type: UNIFORM
        options:
          max_neighbors: 32
      - type: UNIFORM
        options:
          max_neighbors: 32
    eval_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 32
      - type: UNIFORM
        options:
          max_neighbors: 32
      - type: UNIFORM
        options:
          max_neighbors: 32
    layers:
      - - type: EMBEDDING
          output_dim: 32
          bias: true
          init:
            type: GLOROT_NORMAL

      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 32
          output_dim: 32
          bias: true
          init:
            type: GLOROT_NORMAL

      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 32
          output_dim: 32
          bias: true
          init:
            type: GLOROT_NORMAL

      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 32
          output_dim: 32
          bias: true
          init:
            type: GLOROT_NORMAL
  decoder:
    type: DISTMULT
  loss:
    type: SOFTMAX_CE
    options:
      reduction: SUM
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.001
  sparse_optimizer:
    type: ADAGRAD
    options:
      learning_rate: 0.01
storage:
  device_type: cuda
  dataset:
    dataset_dir: /root/all_data/graph_snapshots/initial_snapshot/marius_formatted
  edges:
    type: DEVICE_MEMORY
  embeddings:
    type: DEVICE_MEMORY
  save_model: true
training:
  batch_size: 16
  negative_sampling:
    num_chunks: 10
    negatives_per_positive: 750
    degree_fraction: 0.0
    filtered: false
  num_epochs: 50
  epochs_per_shuffle: 1
evaluation:
  batch_size: 16
  negative_sampling:
    filtered: true