name: Build and Test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.7z",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
        - {
            name: "macOS Latest Clang", artifact: "macOS.7z",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Torch
      working-directory: ${{github.workspace}}
      shell: bash
      run:   |
       if [ "$RUNNER_OS" == "Linux" ]; then
            python3 -m pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
       elif [ "$RUNNER_OS" == "macOS" ]; then
           python3 -m pip install torch==1.7.1
       else
            echo "$RUNNER_OS not supported"
            exit 1
       fi
      
    - name: Install Python Dependencies
      working-directory: ${{github.workspace}}
      shell: bash
      run: python3 -m pip install -r requirements.txt

    - name: Run CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}
        
    - name: CMake Build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=${BUILD_TYPE} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
        buildWithCMake: true
        buildWithCMakeArgs: '-- -j 2'
        buildDirectory: '${{ github.workspace }}/build'

    - name: Run C++ Tests
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)
        set(ENV{CTEST_OUTPUT_ON_FAILURE} "ON")
        execute_process(
          COMMAND ctest -j ${N}
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
          OUTPUT_VARIABLE output
          ERROR_VARIABLE output
          ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE
        )
        if (NOT result EQUAL 0)
          string(REGEX MATCH "[0-9]+% tests.*[0-9.]+ sec.*$" test_results "${output}")
          string(REPLACE "\n" "%0A" test_results "${test_results}")
          message("::error::${test_results}")
          message(FATAL_ERROR "Running tests failed!")
        endif()

    - name: Run Python Tests
      working-directory: ${{github.workspace}}
      shell: bash
      # Run python tests with tox
      run: tox


  packaging:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu Latest GCC", artifact: "Linux.7z",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
          - {
            name: "macOS Latest Clang", artifact: "macOS.7z",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Torch
        working-directory: ${{github.workspace}}
        shell: bash
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
               python3 -m pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          elif [ "$RUNNER_OS" == "macOS" ]; then
              python3 -m pip install torch==1.7.1
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi

      - name: Run Pip Install
        working-directory: ${{github.workspace}}
        shell: bash
        run: python3 -m pip install . --verbose

      - name: Test Pip Install
        working-directory: ${{github.workspace}}
        shell: bash
        run:   |
          python3 -c "import marius as m"
          python3 -c "from marius.tools import preprocess"
          marius_preprocess fb15k output_dir/

