name: Testing DB2GRAPH using postgres
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: python:3.6.15

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installing dependencies
        run: pip3 install -r src/python/tools/db2graph/requirements.txt

      - name: Running pytest
        run: pytest -s test/db2graph/test_postgres.py
        # Environment variables used in the test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port - using default port
          POSTGRES_PORT: 5432